### PR TITLE
fix: default values for unions should only be used when no fields are set

### LINKED ISSUE #162: Initializers in unions don't work as expected
I am not 100% sure what the correct behavior is, and just came across this on one of our schemas.

The unions looks something like:

```thrift
enum NullSentinel {
  IS_NULL = 1,
}

union FieldValue {
  1: optional NullSentinel isNull = NullSentinel.IS_NULL
  2: optional bool boolValue
}
```

The generated code (for `thrift-server`) will look something like:
```ts
export class FieldValue extends thrift.StructLike implements IFieldValue {
    public isNull?: NullSentinel.NullSentinel = NullSentinel.NullSentinel.IS_NULL;
    public boolValue?: boolean;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IFieldValueArgs = {}) {
        super();
        let _fieldsSet: number = 0;
        if (args.isNull != null) {
            _fieldsSet++;
            const value_18: NullSentinel.NullSentinel = args.isNull;
            this.isNull = value_18;
        }
        if (args.boolValue != null) {
            _fieldsSet++;
            const value_19: boolean = args.boolValue;
            this.boolValue = value_19;
        }
        if (_fieldsSet > 1) {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.INVALID_DATA, "TUnion cannot have more than one value");
        }
        else if (_fieldsSet < 1) {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.INVALID_DATA, "TUnion must have one value set");
        }
    }
    public static read(input: thrift.TProtocol): FieldValue {
        return new FieldValue(FieldValueCodec.decode(input));
    }
    public static write(args: IFieldValueArgs, output: thrift.TProtocol): void {
        return FieldValueCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return FieldValueCodec.encode(this, output);
    }
}
```

The issue here is that the union will always set isNull and if a value is passed boolValue, the constructor will end up with both props set.

My initial thought on this was that you should only set initializer values if `_fieldSet  < 1`

### PR DESCRIPTION
**Pull request by kevin-greene-ck**
Resolves #162 

Fixes an issue where defined defaults in unions could result in multiple fields being set.

### CODE REVIEW

**Comment by kevin-greene-ck** [comment]
@hayes This is what I came up with. Look okay to you? Test fixture for this: https://github.com/creditkarma/thrift-typescript/pull/163/files#diff-8b97c3b8f61620cfd5530231d88df535

**Comment by hayes** [comment]
looks good to me!

**Comment by hayes** [comment]
confirmed that this works! thanks for getting this together so quickly.

**Comment by kevin-greene-ck** [comment]
Cool, I'll publish in a few minutes.

**Comment by kevin-greene-ck** [comment]
Released in 3.7.1

**Pull request merged**
